// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS9NKOD3Ewvmdh-6jBkZ5FoQBjrut4bNU',
    appId: '1:902603874193:web:76fac201289e4f9bb04430',
    messagingSenderId: '902603874193',
    projectId: 'mobileapp119-e2313',
    authDomain: 'mobileapp119-e2313.firebaseapp.com',
    storageBucket: 'mobileapp119-e2313.appspot.com',
    measurementId: 'G-87H5CDC1L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrey51V9O_aba-HJDII_Zd1G3hMWmAtnM',
    appId: '1:902603874193:android:499ff2ca29948fcfb04430',
    messagingSenderId: '902603874193',
    projectId: 'mobileapp119-e2313',
    storageBucket: 'mobileapp119-e2313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvguevvvHyIfdTFMo3aLIawIWpcefEg0k',
    appId: '1:902603874193:ios:7b5d6640de98ab53b04430',
    messagingSenderId: '902603874193',
    projectId: 'mobileapp119-e2313',
    storageBucket: 'mobileapp119-e2313.appspot.com',
    iosClientId: '902603874193-7tad2deada5inagvev4184rjrhsb5mjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvguevvvHyIfdTFMo3aLIawIWpcefEg0k',
    appId: '1:902603874193:ios:7b5d6640de98ab53b04430',
    messagingSenderId: '902603874193',
    projectId: 'mobileapp119-e2313',
    storageBucket: 'mobileapp119-e2313.appspot.com',
    iosClientId: '902603874193-7tad2deada5inagvev4184rjrhsb5mjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab7',
  );
}
